### ISSUE TITLE
Would you please update java 8 to 181?

### ISSUE THREAD

**Issue by Mike-the-one** [io-sgr/docker-java-oracle#3]
Hi, @SgrAlpha @deangelo-llooker  I am using java_server_8 on my servers, the current version you have is 172u11, the latest is 181. Would you please update server_8 to 181?  The reason for me is this bug fix:

JDK-8196491

It is in 181, or 172b35

thanks!

**Comment by SgrAlpha** [comment]
Fixed. Now the server_jre_8 is pointed to update 181 build 13

**Comment by SgrAlpha** [comment]
See fb9bc1012f944bfe4913f599fdc03da521d91287
