### ISSUE TITLE
Image sgrio/java-oracle:server_jre_8 not on DockerHub

### ISSUE THREAD

**Issue by SimoneGianni** [io-sgr/docker-java-oracle#4]
Hello, and thanks for your work on these images.

Since 12 hours the image sgrio/java-oracle:server_jre_8 is not on DockerHub anymore. 

https://hub.docker.com/r/sgrio/java-oracle/

Page reports 404.

Is this a temporary outage, or was this image retired?

**Comment by SgrAlpha** [comment]
Unfortunately, due to DMCA, the images have been removed from DockerHub, I will continue to maintain this repo, but you will have to build by you own if needed. Thanks for using.
