### ISSUE TITLE
Looks like this is now failing due to a rework of the Oracle urls

### ISSUE THREAD

**Issue by jamiebbowen** [io-sgr/docker-java-oracle#5]
The following command fails with a 404 (I stripped out all the extra stuff to clearly show the issue):

curl --silent --location --retry 3 --cacert GeoTrust_Global_CA.pem --header "Cookie: oraclelicense=accept-securebackup-cookie;" https://download.oracle.com/otn-pub/java/jdk/12.0.1+12/69cfe15208a647278a19ef0990eea691/jdk-12.0.1_linux-x64_bin.tar.gz

Not sure how to fix it or if it can even be fixed at all.  Let me know if there's anything I can do to help.

Thank you!

**Comment by SgrAlpha** [comment]
This is because Oracle release 12.0.2 and removed the download link to 12.0.1, I will update Dockerfile

**Comment by SgrAlpha** [comment]
Fixed in https://github.com/io-sgr/docker-java-oracle/pull/6
